# Site settings
title: Monte Sua Horta
description: Monte sua horta
url: https://www.mrprompt.com.br
baseurl: "/montesuahorta/" # the subpath of your site, e.g. /blog/

# Build settings
highlighter: rouge
timezone: America/Sao_Paulo
permalink: pretty

# Plugins
gems:
  - jekyll-sitemap

sass:
  style: compressed

defaults:
  - scope:
      path: "assets/img/pet"
    values:
      image: true
      pet: true
  - scope:
      path: "assets/img/vertical"
    values:
      image: true
      vertical: true
  - scope:
      path: "assets/img/composteira"
    values:
      image: true
      composteira: true
  - scope:
      path: "assets/img/pet-5lt"
    values:
      image: true
      pet5lt: true
